version: '3'

services:
    httpd:
        image: atdock/httpd:2.4
        container_name: atdock_httpd
        volumes:
            - "./www:/usr/local/apache2/htdocs"
        networks:
            at_network:
                ipv4_address: 172.27.1.2
        links:
          - php

    php:
        image: atdock/php:7.1
        container_name: atdock_php
        volumes:
            - "./www:/var/www"
        networks:
            at_network:
                ipv4_address: 172.27.1.3

    mysql:
        image: atdock/mysql:5.7
        container_name: atdock_mysql
#        volumes:
#            - ".data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            at_network:
                ipv4_address: 172.27.1.4

networks:
    at_network:
        ipam:
            driver: default
            config:
                - subnet: 172.27.1.0/16
