version: '3'

services:
    httpd:
        image: tuandock/httpd:1.0
        container_name: tuandock_http
        volumes:
            - "www:/var/www"
            - "httpd/logs:/var/log/apache2"
        networks:
            - AMP
        expose:
          - 80
          - 443
          - 9000
        ports:
          - "8080:80"
          - "443:443"
        links:
          - php

    php:
        image: tuandock/php-fpm:1.0
        container_name: tuandock_php
        volumes:
            - "www:/var/www"
            - "php-fpm/logs:/var/log/php7"
        networks:
            - AMP
        expose:
          - 9000
        ports:
          - "9000:9000"
        command: ["php-fpm", "--nodaemonize"]

#    mysql:
#        build: mysql
#        volumes:
#            - ".data/db:/var/lib/mysql"
#        environment:
#            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#            MYSQL_DATABASE: ${MYSQL_DATABASE}
#            MYSQL_USER: ${MYSQL_USER}
#            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
networks:
    AMP:
